import type { AppStore, EstiloQrConfig } from "./types";

export const ESTILO_QR_DEFAULT: EstiloQrConfig = {
  modulos: { forma: "redondeado", color: "#251911", degradado: null },
  ojos: {
    marco: { forma: "cuadrado", color: "#251911", degradado: null },
    centro: { forma: "cuadrado", color: "#251911", degradado: null },
  },
  fondo: { color: "#FFFFFF" },
  margen: 4,
  correccion: "H",
  logo: { tamano: 0.2, margen: 0, ocultarModulos: true },
};

export const SEED_STORE: AppStore = {
  app: "pegatinas-nfc-studio",
  version: 1,
  modelo_kie: "gpt-image-2-image-to-image",
  cola_max_en_vuelo: 3,
  estilos_qr: [
    {
      id: "11111111-1111-4111-8111-111111111111",
      nombre: "Clásico oscuro",
      config: ESTILO_QR_DEFAULT,
      tiene_logo: true,
      creado_en: "2026-09-01T10:00:00.000Z",
      actualizado_en: "2026-09-05T12:00:00.000Z",
      archivado_en: null,
      version: 3,
    },
    {
      id: "22222222-2222-4222-8222-222222222222",
      nombre: "Minimal B/N",
      config: {
        ...ESTILO_QR_DEFAULT,
        modulos: { forma: "cuadrado", color: "#111111", degradado: null },
        logo: { tamano: 0, margen: 0, ocultarModulos: true },
      },
      tiene_logo: false,
      creado_en: "2026-09-02T10:00:00.000Z",
      actualizado_en: "2026-09-02T10:00:00.000Z",
      archivado_en: null,
      version: 1,
    },
  ],
  generaciones: [
    {
      id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
      creado_en: "2026-09-10T10:00:00.000Z",
      iniciado_en: "2026-09-10T10:00:05.000Z",
      estado: "listo",
      fase_qr: null,
      intentos_inicio: 1,
      error_msg: null,
      nombre_negocio: "Café Luna",
      nombre_agencia: "Estudio Norte",
      slug_negocio: "cafe-luna",
      aspect_ratio: "1:1",
      resolucion: "1K",
      estilo_texto: "Paleta cálida, tipografía serif suave",
      qr_modo: "inmutable",
      url_qr: "https://example.com/resenas/cafe-luna",
      qr_estilo_snapshot: ESTILO_QR_DEFAULT,
      qr_artistico_intento: null,
      integracion_intento: null,
      qr_ajustes_aplicados: ["base", "sin_logo_central"],
      coste_ms: 36000,
      tiene_logo: true,
      tiene_estilo: true,
      tiene_logo_qr: true,
      tiene_resultado: true,
      tiene_qr_artistico: false,
      origen: "manual",
      regenerado_desde: null,
      archivo_origen: null,
      prompt_enviado: "PROMPT_FINAL_SNAPSHOT...",
    },
    {
      id: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
      creado_en: "2026-09-10T11:00:00.000Z",
      iniciado_en: "2026-09-10T11:00:04.000Z",
      estado: "generando",
      fase_qr: "integrando_diseno",
      intentos_inicio: 1,
      error_msg: null,
      nombre_negocio: "Bar Sol",
      nombre_agencia: "Pixel & Co",
      slug_negocio: "bar-sol",
      aspect_ratio: "9:16",
      resolucion: "2K",
      estilo_texto: "",
      qr_modo: "artistico_ia",
      url_qr: "https://maps.example/bar-sol/reviews",
      qr_estilo_snapshot: {
        ...ESTILO_QR_DEFAULT,
        modulos: { forma: "cuadrado", color: "#111111", degradado: null },
        logo: { tamano: 0, margen: 0, ocultarModulos: true },
      },
      qr_artistico_intento: 2,
      integracion_intento: 1,
      qr_ajustes_aplicados: [],
      coste_ms: null,
      tiene_logo: true,
      tiene_estilo: false,
      tiene_logo_qr: false,
      tiene_resultado: false,
      tiene_qr_artistico: true,
      origen: "manual",
      regenerado_desde: null,
      archivo_origen: null,
      prompt_enviado: "PROMPT_INTEGRACION_SNAPSHOT...",
    },
    {
      id: "cccccccc-cccc-4ccc-8ccc-cccccccccccc",
      creado_en: "2026-09-10T11:30:00.000Z",
      iniciado_en: "2026-09-10T11:30:03.000Z",
      estado: "revision_necesaria",
      fase_qr: "validando_qr_final",
      intentos_inicio: 1,
      error_msg: "No se pudo garantizar la URL exacta del QR tras degradación",
      nombre_negocio: "Tienda Mar",
      nombre_agencia: "Agencia Sur",
      slug_negocio: "tienda-mar",
      aspect_ratio: "circulo",
      resolucion: "1K",
      estilo_texto: "Minimal, mucho blanco",
      qr_modo: "inmutable",
      url_qr: "https://example.com/r/tienda-mar",
      qr_estilo_snapshot: ESTILO_QR_DEFAULT,
      qr_artistico_intento: null,
      integracion_intento: null,
      qr_ajustes_aplicados: [
        "base",
        "sin_logo_central",
        "sin_degradados",
        "modulos_redondeados",
        "ojos_normalizados",
        "modulos_cuadrados",
      ],
      coste_ms: 36000,
      tiene_logo: true,
      tiene_estilo: false,
      tiene_logo_qr: false,
      tiene_resultado: true,
      tiene_qr_artistico: false,
      origen: "manual",
      regenerado_desde: null,
      archivo_origen: null,
      prompt_enviado: "PROMPT_CIRCULAR_SNAPSHOT...",
    },
    {
      id: "dddddddd-dddd-4ddd-8ddd-dddddddddddd",
      creado_en: "2026-09-10T12:00:00.000Z",
      iniciado_en: null,
      estado: "pendiente",
      fase_qr: null,
      intentos_inicio: 0,
      error_msg: null,
      nombre_negocio: "Boutique Verde",
      nombre_agencia: "Casa Studio",
      slug_negocio: "boutique-verde",
      aspect_ratio: "4:5",
      resolucion: "1K",
      estilo_texto: "Verde oliva y crema",
      qr_modo: "ninguno",
      url_qr: null,
      qr_estilo_snapshot: null,
      qr_artistico_intento: null,
      integracion_intento: null,
      qr_ajustes_aplicados: [],
      coste_ms: null,
      tiene_logo: true,
      tiene_estilo: true,
      tiene_logo_qr: false,
      tiene_resultado: false,
      tiene_qr_artistico: false,
      origen: "importacion",
      regenerado_desde: null,
      archivo_origen: "boutique-verde.zip",
      prompt_enviado: null,
    },
  ],
  importaciones: [],
};
